# I. Numpy

### Импортируйте NumPy

In [2]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [11]:
A = np.zeros(10)
A[4] = 1
A = A.reshape(-1,2)
A

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [77]:
A = np.arange(10, 50)
A = A[::-1]
print(A)
print([i for i in A if i%2==0])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [24]:
v = np.arange(0, 9)
v.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [32]:
v = np.random.rand(4, 3, 2)
print(v)
# v = v.flatten()
max = v.max()
min = v.min()
print(f'max={max}, min={min}')

[[[0.20920651 0.20978388]
  [0.3432827  0.75919727]
  [0.35091932 0.07186016]]

 [[0.82107453 0.44257742]
  [0.40246566 0.95014743]
  [0.73482749 0.99792499]]

 [[0.72025718 0.88815725]
  [0.22718327 0.85404392]
  [0.82752503 0.37695049]]

 [[0.84164685 0.25733434]
  [0.49417318 0.63065935]
  [0.51390518 0.6774319 ]]]
max=0.9979249866533357, min=0.07186015980814175


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [72]:
np.random.seed(123)
A = np.random.randint(1, 11, size=24)
A = A.reshape(6, 4)
print('matrix A:')
print(A)

B = np.random.randint(1, 11, size=12)
B = B.reshape(4, 3)
print('matrix B:')
print(B)

C = np.matmul(A, B)
print('result matrix:')
print(C)

matrix A:
[[ 3  3  7  2]
 [ 4 10  7  2]
 [ 1  2 10  1]
 [ 1 10  4  5]
 [ 1  1  5  2]
 [ 8  4  3  5]]
[[ 8  3  5]
 [ 9  1  8]
 [10  4  5]
 [ 7  2  6]]
result matrix:
[[135  44  86]
 [206  54 147]
 [133  47  77]
 [173  39 135]
 [ 81  28  50]
 [165  50 117]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [67]:
np.random.seed(123)
A = np.random.randint(1, 10, size=49)
A = A.reshape(7, 7)

# массив
print(A)

# среднее
print(A.mean())

# стандартное отклонение
print(np.std(A))

min = np.min(A)
max = np.max(A)

A = A.flatten()
N = np.array([(i - min)/(max - min) for i in A])

N = N.reshape(7, 7)
print(N)


[[3 3 7 2 4 7 2]
 [1 2 1 1 4 5 1]
 [1 5 2 8 4 3 5]
 [8 3 5 9 1 8 4]
 [5 7 2 6 7 3 2]
 [9 4 6 1 3 7 3]
 [5 5 7 4 1 7 5]]
4.244897959183674
2.3778794552864504
[[0.25  0.25  0.75  0.125 0.375 0.75  0.125]
 [0.    0.125 0.    0.    0.375 0.5   0.   ]
 [0.    0.5   0.125 0.875 0.375 0.25  0.5  ]
 [0.875 0.25  0.5   1.    0.    0.875 0.375]
 [0.5   0.75  0.125 0.625 0.75  0.25  0.125]
 [1.    0.375 0.625 0.    0.25  0.75  0.25 ]
 [0.5   0.5   0.75  0.375 0.    0.75  0.5  ]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Загрузите датасет Tips из набора датасетов seaborn

In [2]:
tips = sns.load_dataset('tips')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Посмотрите на первые 5 строчек

In [3]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Узнайте сколько всего строчек и колонок в данных

In [4]:
tips.shape

(244, 7)

### Проверьте есть ли пропуски в данных

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.