# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [3]:
def share_bread(N, K):
    y = 0
    if K % N != 0:
        y = K % N
    x = (K - y) / N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [5]:
def leap_year(year):
    if year % 4 != 0:
        text_result = 'YOU SHALL NOT PASS'
    elif year % 100 == 0:
        if year % 400 == 0:
            text_result = 'YOU SHALL PASS'
        else:
            text_result = 'YOU SHALL NOT PASS'
    else:
        text_result = 'YOU SHALL PASS'
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [11]:
import math

def amulet_area(a, b, c):
    p = (a + b + c) / 2
    S = math.sqrt(p*(p - a)*(p - b)*(p - c))
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2} $$

In [21]:
import math
import numpy as np

def cal_euclidean(a, b):
    sum = 0
    for i in range(len(a)):
        sum += (a[i] - b[i])**2
    distance = math.sqrt(sum)
    return distance

def cal_manhattan(a, b):
    distance = 0
    for i in range(len(a)):
        distance += np.abs(a[i] - b[i])
    return distance

def cal_cosine(a, b):
    scalar_product = 0
    for i in range(len(a)):
        scalar_product += (a[i] * b[i])

    summ_squares_a = 0
    for i in range(len(a)):
        summ_squares_a += a[i]**2
    norm_a = math.sqrt(summ_squares_a)

    summ_squares_b = 0
    for i in range(len(b)):
        summ_squares_b += b[i]**2
    norm_b = math.sqrt(summ_squares_b)

    distance = 1 - scalar_product / norm_a * norm_b
    return distance

In [22]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

33.896902513356586
99
147.5334348217538


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [31]:
my_array = np.random.rand(100)
print(np.max(my_array), np.min(my_array))
sorted_array = np.sort(my_array)
sorted_array[0] = 0
sorted_array[99] = 1
print(sorted_array)

0.9994302704527215 0.01784056324540295
[0.         0.02275423 0.02891095 0.0379866  0.06411677 0.07622491
 0.0833659  0.08553008 0.10194396 0.13494535 0.13578161 0.1484687
 0.17946583 0.23107882 0.23731334 0.23827251 0.27732597 0.28397988
 0.29417502 0.29739585 0.31566179 0.32246687 0.32603895 0.32852605
 0.33154483 0.35406075 0.35491889 0.36142571 0.37071341 0.37980577
 0.382405   0.38953081 0.39049173 0.39049308 0.40500119 0.4084554
 0.4143194  0.41984278 0.43929914 0.44698923 0.47120003 0.47241158
 0.48623921 0.49193503 0.4964774  0.50244017 0.50822445 0.50840006
 0.51316422 0.52928509 0.53535459 0.53946727 0.54921198 0.56834166
 0.57089352 0.57228577 0.57411359 0.5836419  0.59065618 0.59279411
 0.60766183 0.63768514 0.64667579 0.65135096 0.65806698 0.65970961
 0.66373659 0.66537126 0.70314695 0.70619257 0.7330592  0.74461125
 0.75436664 0.75863413 0.78838834 0.80770637 0.80991205 0.821671
 0.82429148 0.83308462 0.85025516 0.86250744 0.86845429 0.88430557
 0.89825132 0.90466343 0.91

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [50]:
my_array = np.random.randint(0, 50, (5, 6))
selected_column = np.argmax(my_array.max(axis=0)) + 1
print('Shape: ', my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[19 25 38 32 12 20]
 [38 41 19 39  0 44]
 [46  4 15 29 47  2]
 [48 12  7 33 30  9]
 [25 16 28 21 16 49]]
6


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [81]:
def get_unique_rows(X):
    X_unique = np.unique(X, axis=0)
    return X_unique

In [84]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 5 4]
 [5 4 4]
 [5 5 5]
 [4 5 5]
 [5 5 5]
 [5 5 5]
 [4 5 4]
 [4 5 4]
 [4 4 4]
 [5 5 5]]


In [85]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 5, 4],
       [4, 5, 5],
       [5, 4, 4],
       [5, 5, 5]])